// Generated by GitHub Copilot
import { useRef, useEffect, useState } from 'react';
import styles from './CommandInput.module.css';
import { COMMAND_QUICKSTART } from '../../utils/commandSuggestions';
import { useHistoryAutocomplete } from '../../hooks/useHistoryAutocomplete';
import TerminalPromptIcon from '../../icons/TerminalPromptIcon.svg?react';

interface CommandInputProps {
  command:      string;
  onChange:     (value: string) => void;
  onKeyDown:    (e: React.KeyboardEvent<HTMLElement>) => void;
  onSend:       () => void;
  sendDisabled: boolean;
  disabled:     boolean;
  /** Ordered command history (newest-first), used for history-based autocomplete. */
  history:      string[];
}

/**
 * Chat-style command input with an auto-grow textarea and history-based autocomplete.
 * Enter sends · Shift+Enter inserts a newline · ↑↓ navigates history · Tab accepts suggestion.
 *
 * Accessibility (WCAG 2.1 AA): the textarea implements the ARIA combobox+listbox pattern.
 * Focus never leaves the textarea; the dropup is navigated via aria-activedescendant.
 * The dropup container is always in the DOM so aria-controls always resolves.
 */
export default function CommandInput({
  command,
  onChange,
  onKeyDown,
  onSend,
  sendDisabled,
  disabled,
  history,
}: CommandInputProps) {
  const textareaRef = useRef<HTMLTextAreaElement>(null);
  const paletteWrapperRef = useRef<HTMLSpanElement>(null);
  const paletteRef = useRef<HTMLDivElement>(null);

  // Command palette — tracks whether the popover is pinned open via click.
  const [isPaletteOpen, setIsPaletteOpen] = useState(false);

  // Close the palette on outside click.
  useEffect(() => {
    if (!isPaletteOpen) return;
    const handler = (e: MouseEvent) => {
      if (paletteWrapperRef.current && !paletteWrapperRef.current.contains(e.target as Node)) {
        setIsPaletteOpen(false);
      }
    };
    document.addEventListener('mousedown', handler);
    return () => document.removeEventListener('mousedown', handler);
  }, [isPaletteOpen]);

  // History-based autocomplete state — drives the dropup.
  const ac = useHistoryAutocomplete(history, command);

  // Auto-grow: runs on every command change, including programmatic changes
  // from history navigation (which do not fire onChange). This is the single
  // canonical resize trigger — no duplicate logic in onChange is needed.
  useEffect(() => {
    const el = textareaRef.current;
    if (!el) return;
    // Collapse to 'auto' first to get the true scrollHeight, then expand.
    // Reading scrollHeight forces a synchronous reflow so the intermediate
    // height: auto state is never painted — there is no visible flash.
    el.style.height = 'auto';
    el.style.height = `${el.scrollHeight}px`;
  }, [command]);

  const placeholder = disabled
    ? 'Not connected'
    : 'Enter command (Enter to send · Shift+Enter for new line)';

  const hint = disabled
    ? 'Enter your test message once it is connected'
    : 'Enter to send · Shift+Enter for new line · ↑↓ for history';

  const handleKeyDown = (e: React.KeyboardEvent<HTMLTextAreaElement>) => {
    // ── 1. Tab ────────────────────────────────────────────────────────────
    // Phase 2: accept the active suggestion (or first) when the dropup is open.
    // Falls through to no-op (Phase 1 contract) when the dropup is closed.
    if (e.key === 'Tab') {
      e.preventDefault();
      if (ac.isOpen && ac.suggestions.length > 0) {
        ac.onTab(v => onChange(v));
        // Place caret at end-of-text after React commits the new value.
        // ac.onTab/accept has no access to textareaRef, so the rAF lives here.
        requestAnimationFrame(() => {
          const el = textareaRef.current;
          if (el) el.selectionStart = el.selectionEnd = el.value.length;
        });
      }
      return;
    }

    // ── 2. Enter ──────────────────────────────────────────────────────────
    if (e.key === 'Enter') {
      if (e.shiftKey) {
        // Shift+Enter: let the browser insert a newline — textarea grows via useEffect.
        return;
      }
      e.preventDefault();

      // Ctrl/⌘+Enter or plain Enter: accept highlighted suggestion when dropup is open.
      if (ac.isOpen && ac.activeIndex >= 0) {
        ac.accept(ac.activeIndex, v => onChange(v));
        requestAnimationFrame(() => {
          const el = textareaRef.current;
          if (el) el.selectionStart = el.selectionEnd = el.value.length;
        });
        textareaRef.current?.focus();
        return;
      }

      // Otherwise: send.
      onSend();
      textareaRef.current?.focus();
      return;
    }

    // ── 3. Escape ─────────────────────────────────────────────────────────
    if (e.key === 'Escape') {
      if (ac.isOpen) {
        ac.dismiss();
        e.preventDefault();
        return;
      }
      // Dropup closed — not consumed; browser default applies.
      return;
    }

    // ── 4. ArrowUp / ArrowDown ────────────────────────────────────────────
    if (e.key === 'ArrowUp' || e.key === 'ArrowDown') {
      // When the dropup is visible, intercept all arrow key presses for dropup navigation.
      if (ac.isOpen && ac.suggestions.length > 0) {
        e.preventDefault();
        ac.navigate(e.key === 'ArrowDown' ? 1 : -1);
        return;
      }

      // Dropup closed (or empty) — boundary-aware history navigation.
      const el = textareaRef.current;
      if (el) {
        const { selectionStart, value } = el;
        const beforeCaret = value.slice(0, selectionStart);
        const isFirstLine  = !beforeCaret.includes('\n');
        const isLastLine   = !value.slice(selectionStart).includes('\n');

        const atBoundary =
          (e.key === 'ArrowUp'   && isFirstLine) ||
          (e.key === 'ArrowDown' && isLastLine);

        if (!atBoundary) {
          // Let the browser move the caret within the textarea.
          return;
        }
      }
      // At boundary — delegate to the history handler in the parent hook.
      onKeyDown(e);
      // After React commits the new command value, place the caret at end-of-text
      // so the boundary guard works correctly on the next arrow-key press.
      requestAnimationFrame(() => {
        const el = textareaRef.current;
        if (el) {
          el.selectionStart = el.selectionEnd = el.value.length;
        }
      });
      return;
    }

    // ── 5. All other keys ─────────────────────────────────────────────────
    onKeyDown(e);
  };

  return (
    <div className={styles.commandInput}>
      {/* Label row */}
      <div className={styles.labelRow}>
        <div className={styles.labelGroup}>
          <label htmlFor="command" className={styles.label}>Command</label>
          <span
            ref={paletteWrapperRef}
            className={styles.infoWrapper}
          >
            <button
              type="button"
              className={`${styles.paletteToggle}${isPaletteOpen ? ` ${styles.paletteToggleActive}` : ''}`}
              aria-label="Toggle command palette"
              aria-expanded={isPaletteOpen}
              aria-controls="command-palette"
              onClick={() => setIsPaletteOpen(o => !o)}
              onKeyDown={(e) => {
                // ArrowDown from the toggle button opens the palette and focuses the first item.
                if (e.key === 'ArrowDown' && isPaletteOpen) {
                  e.preventDefault();
                  const first = paletteRef.current?.querySelector<HTMLElement>('[role="option"]');
                  first?.focus();
                }
              }}
              title="Command palette"
            >
              <TerminalPromptIcon aria-hidden="true" focusable="false" />
            </button>
            <div
              id="command-palette"
              ref={paletteRef}
              className={`${styles.popover}${isPaletteOpen ? ` ${styles.popoverOpen}` : ''}`}
              role="listbox"
              aria-label="Command palette"
              onKeyDown={(e) => {
                if (e.key === 'ArrowDown' || e.key === 'ArrowUp') {
                  e.preventDefault();
                  const items = paletteRef.current?.querySelectorAll<HTMLElement>('[role="option"]');
                  if (!items || items.length === 0) return;
                  const idx = Array.from(items).indexOf(document.activeElement as HTMLElement);
                  if (e.key === 'ArrowDown') {
                    // idx === -1 (no item focused yet) → focus first; otherwise advance with wrap.
                    items[idx < 0 ? 0 : (idx + 1) % items.length].focus();
                  } else {
                    items[idx <= 0 ? items.length - 1 : idx - 1].focus();
                  }
                } else if (e.key === 'Escape') {
                  e.preventDefault();
                  setIsPaletteOpen(false);
                  textareaRef.current?.focus();
                }
              }}
            >
              <p className={styles.popoverTitle}>Command palette — click to insert</p>
              {COMMAND_QUICKSTART.map(({ keyword, alias, description, template }) => (
                <div
                  key={keyword}
                  className={styles.popoverRow}
                  role="option"
                  aria-selected={false}
                  tabIndex={isPaletteOpen ? 0 : -1}
                  onMouseDown={e => e.preventDefault()}
                  onClick={() => {
                    onChange(template);
                    setIsPaletteOpen(false);
                    textareaRef.current?.focus();
                  }}
                  onKeyDown={(e) => {
                    if (e.key === 'Enter' || e.key === ' ') {
                      e.preventDefault();
                      onChange(template);
                      setIsPaletteOpen(false);
                      textareaRef.current?.focus();
                    }
                  }}
                >
                  <span className={styles.popoverKeyword}>{keyword}</span>
                  <span className={styles.popoverDesc}>
                    {description}
                    {alias && (
                      <span className={styles.popoverAlias}> · alias: {alias}</span>
                    )}
                  </span>
                </div>
              ))}
            </div>
          </span>
        </div>
      </div>

      {/* Input row: inputWrapper (textarea + dropup) and Send button share one horizontal layout.
          align-items: flex-end keeps the Send button anchored to the bottom
          as the textarea grows. */}
      <div className={styles.inputRow}>
        {/* inputWrapper provides position:relative so the dropup can be absolutely positioned. */}
        <div className={styles.inputWrapper}>
          {/* Dropup — always rendered so aria-controls always resolves to a real DOM element.
              Visibility is toggled via the `hidden` attribute; items rendered only when visible. */}
          <div
            id="history-dropup"
            role="listbox"
            aria-label="Command history suggestions"
            className={styles.dropup}
            hidden={!(ac.isOpen && ac.suggestions.length > 0)}
          >
            {/* Header label — identifies the panel as history-based autocomplete.
                aria-hidden so screen readers don't announce it as a listbox option. */}
            <div className={styles.dropupHeader} aria-hidden="true">
              Recent Commands
            </div>
            {ac.isOpen && ac.suggestions.length > 0 && ac.suggestions.map((entry, i) => {
              const firstLine = entry.split('\n')[0];
              const isMultiLine = entry.includes('\n');
              // Bold the matched prefix so the user sees which characters they typed.
              // Use only the first line of the needle to avoid a multiline-needle
              // length exceeding firstLine.length (§13.10).
              const needle = command.trimStart().split('\n')[0];
              const matchLen = Math.min(needle.length, firstLine.length);
              const boldPart   = firstLine.slice(0, matchLen);
              const normalPart = firstLine.slice(matchLen);
              return (
                <div
                  key={entry}
                  id={`history-option-${i}`}
                  role="option"
                  aria-selected={i === ac.activeIndex}
                  className={styles.dropupItem}
                  onMouseDown={e => e.preventDefault()}
                  onClick={() => {
                    ac.accept(i, v => onChange(v));
                    // Place caret at end-of-text after React commits the new value.
                    // ac.accept() has no access to textareaRef, so the rAF lives here.
                    requestAnimationFrame(() => {
                      const el = textareaRef.current;
                      if (el) el.selectionStart = el.selectionEnd = el.value.length;
                    });
                  }}
                >
                  <span className={styles.dropupItemText}>
                    {matchLen > 0 && <strong className={styles.matchHighlight}>{boldPart}</strong>}
                    {normalPart}{isMultiLine ? '\u2026' : ''}
                  </span>
                  {isMultiLine && (
                    <span className={styles.multilineIndicator} aria-label="multi-line command">↵</span>
                  )}
                </div>
              );
            })}
          </div>

          <textarea
            ref={textareaRef}
            id="command"
            role="combobox"
            aria-expanded={ac.isOpen && ac.suggestions.length > 0}
            aria-haspopup="listbox"
            aria-controls="history-dropup"
            aria-activedescendant={
              ac.isOpen && ac.suggestions.length > 0 && ac.activeIndex >= 0
                ? `history-option-${ac.activeIndex}`
                : undefined
            }
            aria-autocomplete="list"
            className={styles.textarea}
            rows={1}
            placeholder={placeholder}
            value={command}
            disabled={disabled}
            onChange={(e) => {
              // Ordering: update command value first so the useMemo in the hook
              // computes suggestions against the already-updated value in the
              // same React 19 batched render that flips isOpen to true.
              onChange(e.target.value);
              ac.onCommandChange();
            }}
            onKeyDown={handleKeyDown}
            onBlur={() => ac.dismiss()}
            autoComplete="off"
            autoCorrect="off"
            spellCheck={false}
          />
        </div>

        <button
          className={styles.sendButton}
          onClick={() => { onSend(); textareaRef.current?.focus(); }}
          disabled={sendDisabled}
          aria-label="Send command"
        >
          Send
        </button>
      </div>

      {hint && <p className={styles.hint}>{hint}</p>}
    </div>
  );
}

