image: maven:3.6.1-jdk-8

variables:
    MAVEN_CLI_OPTS: "--show-version"
    MAVEN_OPTS: "-Dmaven.repo.local=$CI_PROJECT_DIR/.m2/repository -Djava.awt.headless=true"

cache:
    key: $CI_PIPELINE_IID
    policy: pull
    paths:
    - $CI_PROJECT_DIR/.m2/repository # cache maven repository across all jobs

include:
    - template: Code-Quality.gitlab-ci.yml
  
 
stages:
    - build
    - test
    - package
    - deploy
    
build:
    stage: build
    script:
        - mvn $MAVEN_CLI_OPTS clean compile install -f system/platform-core
        - mvn $MAVEN_CLI_OPTS clean compile install -f system/rest-core
        - mvn $MAVEN_CLI_OPTS clean compile install -f system/rest-spring
        - mvn $MAVEN_CLI_OPTS clean compile install -f system/rest-spring
        - mvn $MAVEN_CLI_OPTS clean compile install -f connectors/hazelcast/hazelcast-connector
        - mvn $MAVEN_CLI_OPTS clean compile install -f connectors/kafka/kafka-connector
    cache:
        key: $CI_PIPELINE_IID
        policy: push # this is the only job that needs to publish to the cache, therefore it is overriding the policy
        paths:
            - $CI_PROJECT_DIR/.m2/repository
            
test_and_coverage:
    stage: test
    script:
        - mvn $MAVEN_CLI_OPTS test -f system/platform-core
        - ls -la
        - ls -la system/platform-core/target
        - ls -la system/platform-core/target/site
        - ls -la system/platform-core/target/site/jacoco
        - cat system/platform-core/target/site/jacoco/index.html
        - mv system/platform-core/target/site/jacoco target/jacoco/
    coverage: '/Total.*?([0-9]{1,3})%/'
    artifacts:
        reports:
            junit:
                - target/surefire-reports/TEST-*.xml
        paths:
            - target/jacoco
        expire_in: 30 days
 