// Generated by GitHub Copilot
import { useState, useMemo } from 'react';
import { MAX_AUTOCOMPLETE_SUGGESTIONS } from '../config/playgrounds';

export interface UseHistoryAutocompleteReturn {
  /** Filtered, deduplicated history suggestions. Newest-first, capped at MAX_AUTOCOMPLETE_SUGGESTIONS. */
  suggestions: string[];
  /** Whether the dropup is currently open. */
  isOpen: boolean;
  /** Index of the keyboard-highlighted row. -1 = none. */
  activeIndex: number;
  /**
   * Call on every real onChange event. Flips isOpen to true and resets activeIndex.
   * Must NOT be called after programmatic command changes (history nav dispatches).
   * Zero-argument: the current command is already reflected via useMemo.
   *
   * NOTE: diverges intentionally from the dormant useAutocomplete.onCommandChange
   * signature `(value: string) => void` — this hook takes no arguments.
   * TypeScript will catch any accidental extra argument at compile time.
   */
  onCommandChange: () => void;
  /**
   * Move the highlight by `direction` rows (+1 = down, -1 = up).
   * Wraps around at both ends: ArrowDown on last item → index 0;
   * ArrowUp on index 0 → last item; ArrowUp from -1 → last item (DP-2: A).
   */
  navigate: (direction: 1 | -1) => void;
  /**
   * Accept the suggestion at `index` and insert it via `setCommand`.
   * Explicit `index` supports both keyboard (pass ac.activeIndex) and
   * mouse-click (pass the map index `i`) call sites.
   * Closes the dropup and resets activeIndex to -1.
   */
  accept: (index: number, setCommand: (v: string) => void) => void;
  /**
   * Handle a Tab keypress.
   *  - Dropup open with suggestions: accepts active item (or index 0 if activeIndex = -1).
   *  - Dropup closed or no suggestions: no-op (DP-3: C).
   */
  onTab: (setCommand: (v: string) => void) => void;
  /** Close the dropup without changing the command text. */
  dismiss: () => void;
}

/**
 * Provides history-based command autocomplete for the CommandInput component.
 *
 * Filtering and deduplication run in a single useMemo over [history, command].
 * All state mutations are synchronous; the React Compiler handles memoisation
 * of the returned callbacks — no manual useCallback wrappers are needed.
 *
 * Accessibility: drives the ARIA combobox+listbox pattern in CommandInput.
 * Focus never leaves the textarea; navigation is via aria-activedescendant.
 */
export function useHistoryAutocomplete(
  history: string[],
  command: string,
): UseHistoryAutocompleteReturn {
  const [isOpen, setIsOpen] = useState(false);
  const [activeIndex, setActiveIndex] = useState(-1);

  // Single useMemo: filter → deduplicate → cap.
  // Recomputes only when history array reference or command string changes.
  const suggestions = useMemo(() => {
    const needle = command.trimStart();
    if (needle.length === 0) return [];

    const lowerNeedle = needle.toLowerCase();
    const allMatching = history.filter(entry =>
      entry.toLowerCase().startsWith(lowerNeedle),
    );

    // Deduplicate: keep first (most recent) occurrence of any duplicate.
    const seen = new Set<string>();
    const deduped = allMatching.filter(entry => {
      if (seen.has(entry)) return false;
      seen.add(entry);
      return true;
    });

    return deduped.slice(0, MAX_AUTOCOMPLETE_SUGGESTIONS);
  }, [history, command]);

  const onCommandChange = () => {
    setIsOpen(true);
    setActiveIndex(-1);
  };

  const navigate = (direction: 1 | -1) => {
    const n = suggestions.length;
    // Guard: no-op when list is empty (prevents % 0 = NaN).
    if (n === 0) return;
    setActiveIndex(i => {
      if (direction === 1) {
        // ArrowDown: -1 → 0, last → 0 (wrap).
        return i < 0 ? 0 : (i + 1) % n;
      } else {
        // ArrowUp: 0 or -1 → last (wrap), otherwise decrement.
        return i <= 0 ? n - 1 : i - 1;
      }
    });
  };

  const accept = (index: number, setCommand: (v: string) => void) => {
    if (index >= 0 && index < suggestions.length) {
      setCommand(suggestions[index]);
    }
    setIsOpen(false);
    setActiveIndex(-1);
  };

  const onTab = (setCommand: (v: string) => void) => {
    // No-op when closed or when there are no suggestions (DP-3: C).
    if (!isOpen || suggestions.length === 0) return;
    const index = activeIndex >= 0 ? activeIndex : 0;
    accept(index, setCommand);
  };

  const dismiss = () => {
    setIsOpen(false);
    setActiveIndex(-1);
  };

  return { suggestions, isOpen, activeIndex, onCommandChange, navigate, accept, onTab, dismiss };
}
