//
// Copyright 2018-2026 Accenture Technology
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//

//! Packages the skill snapshot at build time - the analog of the Java module's
//! Maven resource includes (which copied `docs/` into the jar). The inventory
//! in `resources/skill/files.list` drives everything: each entry is validated,
//! resolved to its source file (`SKILL.md`/`security.json` from the skill
//! resources; `references/<path>` from the repo's `docs/<path>`), and embedded
//! with `include_bytes!` into a generated table. A missing source fails the
//! build, so the inventory cannot drift from the documentation tree - and the
//! compiled binary is self-contained (the nested-jar-safety analog).

use std::collections::HashSet;
use std::env;
use std::fs;
use std::path::{Path, PathBuf};

fn main() {
    let manifest = PathBuf::from(env::var("CARGO_MANIFEST_DIR").expect("manifest dir"));
    let repo = manifest
        .join("../..")
        .canonicalize()
        .expect("repository root");
    let list_path = manifest.join("resources/skill/files.list");
    println!("cargo:rerun-if-changed={}", list_path.display());
    let list = fs::read_to_string(&list_path).expect("read files.list");
    let mut seen: HashSet<String> = HashSet::new();
    let mut entries: Vec<(String, PathBuf)> = Vec::new();
    for line in list.lines() {
        let entry = line.trim();
        if entry.is_empty() {
            continue;
        }
        assert!(
            !entry.starts_with('/')
                && !entry.starts_with('.')
                && !entry.contains("..")
                && !entry.contains('\\')
                && !entry.contains(':')
                && seen.insert(entry.to_string()),
            "Invalid files.list entry: {entry}"
        );
        let source = source_for(&manifest, &repo, entry);
        assert!(
            source.is_file(),
            "files.list entry has no source file: {entry} -> {}",
            source.display()
        );
        println!("cargo:rerun-if-changed={}", source.display());
        entries.push((entry.to_string(), source));
    }
    assert!(!entries.is_empty(), "files.list must not be empty");
    entries.sort_by(|a, b| a.0.cmp(&b.0));
    let mut generated = String::from(
        "/// Generated by build.rs from resources/skill/files.list - the packaged\n\
         /// snapshot inventory (path -> bytes), embedded at compile time.\n\
         pub static SKILL_FILES: &[(&str, &[u8])] = &[\n",
    );
    for (entry, source) in &entries {
        generated.push_str(&format!(
            "    ({entry:?}, include_bytes!({:?})),\n",
            source.display().to_string()
        ));
    }
    generated.push_str("];\n");
    let out = PathBuf::from(env::var("OUT_DIR").expect("out dir")).join("skill_files.rs");
    fs::write(out, generated).expect("write generated inventory");
}

/// Map one inventory entry to its source file.
fn source_for(manifest: &Path, repo: &Path, entry: &str) -> PathBuf {
    match entry {
        "SKILL.md" => manifest.join("resources/skill/SKILL.md"),
        "security.json" => manifest.join("resources/skill/security.json"),
        other => {
            let rest = other.strip_prefix("references/").unwrap_or_else(|| {
                panic!("Snapshot entry must be SKILL.md, security.json or references/*: {other}")
            });
            repo.join("docs").join(rest)
        }
    }
}
